### ISSUE TITLE
example "read-repeat.c" output in fahrenheit

### ISSUE THREAD

**Issue by virtualronb** [rcrum003/TEMPered-v6-2015#1]
Love this tool...

Not an experienced C programmer... could someone perhaps show me how to get output in Fahrenheit?
Thanks!
Ron

**Comment by rcrum003** [comment]
Take a look at temp-scale.c in the libtempered-util folder if you are making your own code. Linked below.

If you are just using the code as is, use "tempered -s F" to get the output in F.

https://github.com/rcrum003/TEMPered-v6-2015/blob/master/libtempered-util/temp-scale.c

**Comment by virtualronb** [comment]
Thanks, that will help!
I was looking at the "read-repeat" program in the examples directory,
getting that to output in F.
(probably should just learn Celsius ;)

Thanks again.

**Comment by virtualronb** [comment]
Thanks again.
I just slapped this formula in above the print line....
 tempF = tempC \* 9 / 5 +32;
 printf( " %.2f°F", tempF );

not sure if ugly or not, but it worked :)

**Comment by rcrum003** [comment]
Yep,
That works.
